name: Simple_Draw_Paint
description: This is Simple Draw Paint App .

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Multi language
  flutter_localizations:
    sdk: flutter
  image_painter:
    path: packages/image_painter/
  intl: ^0.17.0
  open_file: ^3.2.1
  path_provider: ^2.0.9
  cupertino_icons: ^1.0.5
  google_mobile_ads: ^2.1.0
  image_gallery_saver: ^1.7.1
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true #追加

assets:
  - assets/images

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
